services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  file-finder:
    image: dbsanfte/indexer:latest
    container_name: file-finder
    restart: unless-stopped
    build:
      context: ./indexer
    command:
      - "--file-finder"
    depends_on:
      - rabbitmq
    environment:
      - LOG_LEVEL=debug
      - ELASTICSEARCH_HOST=http://192.168.50.100
      - ELASTICSEARCH_PORT=31200
      - ELASTICSEARCH_SSL_SHOW_WARN=false
      - ELASTICSEARCH_SSL_VERIFY_CERTS=false
      - ELASTICSEARCH_INDEX=eq-archive-0
      - REINDEXING_ENABLED=false
#     - SPARSE_CHECKOUT_PATHS=websites/eq.castersrealm.com,mailing-lists/EQ-Clerics,newsgroups
      - SPARSE_CHECKOUT_PATHS=websites/eq.castersrealm.com
#     - SPARSE_CHECKOUT_PATHS=mailing-lists/EQ-Clerics
      - GIT_REPO_URL=https://github.com/dbsanfte/eq-archives.git
      - LOCAL_REPO_PATH=/data/eq-archives
      - SLEEP_INTERVAL=3600
    volumes:
      - eq-archives-volume:/data
    secrets:
      - es_username
      - es_password

  indexer:
    image: dbsanfte/indexer:latest
    restart: unless-stopped
    deploy:
      replicas: 1
    command:
      - "--indexer"
    depends_on:
      - rabbitmq
      - file-finder
    environment:
      - LOG_LEVEL=debug
      - ELASTICSEARCH_HOST=http://192.168.50.100
      - ELASTICSEARCH_PORT=31200
      - ELASTICSEARCH_SSL_SHOW_WARN=false
      - ELASTICSEARCH_SSL_VERIFY_CERTS=false
      - ELASTICSEARCH_INDEX=eq-archive-0
      - LOCAL_REPO_PATH=/data/eq-archives
      - SKIP_IMAGE_FILES=true
      - SKIP_OTHER_FILES=true
      - OPENAI_ENDPOINT=http://192.168.50.139:1234/v1
      - OPENAI_API_KEY=lmstudio
      - OPENAI_TEXT_MODEL_NAME=phi-4@q6_k
      - OPENAI_TEXT_TEMPERATURE=0.015
      - OPENAI_IMAGE_MODEL_NAME=llava-v1.5-7b@q8_0
      - OPENAI_EMBEDDING_MODEL_NAME=text-embedding-nomic-embed-text-v1.5@q8_0
    volumes:
      - eq-archives-volume:/data
    secrets:
      - es_username
      - es_password
      - openai_api_key

  indexer-2:
    image: dbsanfte/indexer:latest
    restart: unless-stopped
    deploy:
      replicas: 1
    command:
      - "--indexer"
    depends_on:
      - rabbitmq
      - file-finder
    environment:
      - LOG_LEVEL=debug
      - ELASTICSEARCH_HOST=http://192.168.50.100
      - ELASTICSEARCH_PORT=31200
      - ELASTICSEARCH_SSL_SHOW_WARN=false
      - ELASTICSEARCH_SSL_VERIFY_CERTS=false
      - ELASTICSEARCH_INDEX=eq-archive-0
      - LOCAL_REPO_PATH=/data/eq-archives
      - SKIP_IMAGE_FILES=true
      - SKIP_OTHER_FILES=true
      - OPENAI_ENDPOINT=http://192.168.50.145:1234/v1
      - OPENAI_API_KEY=lmstudio
      - OPENAI_TEXT_MODEL_NAME=phi-4@q6_k
      - OPENAI_TEXT_TEMPERATURE=0.015
      - OPENAI_IMAGE_MODEL_NAME=llava-v1.5-7b@q8_0
      - OPENAI_EMBEDDING_MODEL_NAME=text-embedding-nomic-embed-text-v1.5@q8_0
    volumes:
      - eq-archives-volume:/data
    secrets:
      - es_username
      - es_password
      - openai_api_key

  frontend:
    image: dbsanfte/frontend:latest
    restart: unless-stopped
    deploy:
      replicas: 1
    build:
      context: ./frontend
    ports:
      - "3030:80"
    environment:
      - LOG_LEVEL=debug
      - ELASTICSEARCH_URL=http://192.168.50.100:31200
      - OPENAI_URL=http://192.168.50.139:1234
      - ELASTICSEARCH_INDEX=eq-archive
    secrets:
      - es_readonly_username
      - es_readonly_password
      - openai_api_key

volumes:
  es-data:
  rabbitmq-data:
  eq-archives-volume:

secrets:
  es_username:
    file: ./elastic.username.secret.txt
  es_password:
    file: ./elastic.password.secret.txt
  es_readonly_username:
    file: ./elastic.readonly.username.secret.txt  
  es_readonly_password:
    file: ./elastic.readonly.password.secret.txt  
  openai_api_key:
    file: ./openai_api_key.secret.txt