# 01-pv-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eq-archives-pvc
  namespace: eq-archive
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: # set this to the name of your storage class if needed
