name: release-please

on:
  push:
    branches: [ "master" ]
    
jobs:
  release-please:
    runs-on: eqvm
    steps:
      - name: release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          package-name: ${{ github.event.repository.name }}
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
